#include <revolution/VF.h>

int VFiPFCODE_Combine_Width(s16 oem_width, s16 uni_width) {
    return (oem_width << 16) + uni_width;
}

void VFiPFCODE_Divide_Width(u32 width, s16* oem_width, s16* uni_width) {
    *oem_width = width >> 16;
    *uni_width = width;
}

const u8 VFipf_valid_fn_char[VF_FN_MAX_CHAR - VF_FN_MIN_CHAR] = {
    PFCODE_FN_VALID_LONG,                           //!<  (Space)
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< !
    PFCODE_FN_INVALID,                              //!< "
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< #
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< $
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< %
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< &
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< '
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< (
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< )
    PFCODE_FN_INVALID,                              //!< *
    PFCODE_FN_VALID_LONG,                           //!< +
    PFCODE_FN_VALID_LONG,                           //!< ,
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< -
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< .
    PFCODE_FN_INVALID,                              //!< /
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 0
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 1
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 2
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 3
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 4
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 5
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 6
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 7
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 8
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< 9
    PFCODE_FN_INVALID,                              //!< :
    PFCODE_FN_VALID_LONG,                           //!< ;
    PFCODE_FN_INVALID,                              //!< <
    PFCODE_FN_VALID_LONG,                           //!< =
    PFCODE_FN_INVALID,                              //!< >
    PFCODE_FN_INVALID,                              //!< ?
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< @
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< A
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< B
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< C
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< D
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< E
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< F
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< G
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< H
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< I
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< J
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< K
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< L
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< M
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< N
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< O
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< P
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< Q
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< R
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< S
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< T
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< U
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< V
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< W
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< X
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< Y
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< Z
    PFCODE_FN_VALID_LONG,                           //!< [
    PFCODE_FN_INVALID,                              //!< \ (Backslash)
    PFCODE_FN_VALID_LONG,                           //!< ]
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< ^
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< _
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< `
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< a
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< b
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< c
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< d
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< e
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< f
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< g
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< h
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< i
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< j
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< k
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< l
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< m
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< n
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< o
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< p
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< q
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< r
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< s
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< t
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< u
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< v
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< w
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< x
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< y
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< z
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< {
    PFCODE_FN_INVALID,                              //!< |
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< }
    (PFCODE_FN_VALID_LONG | PFCODE_FN_VALID_SHORT), //!< ~
    PFCODE_FN_INVALID                               //!< DEL
};
