#include "pf_code.h"

#define VF_FN_MIN_CHAR 0x20 // (Space)
#define VF_FN_MAX_CHAR 0x80 // (DEL)

int VFiPFCODE_Combine_Width(s16 lo, s16 hi) { return (lo << 16) + hi; }

void VFiPFCODE_Divide_Width(u32 ch, s16* loOut, s16* hiOut) {
    *loOut = ch >> 16;
    *hiOut = ch;
}

const u8 VFipf_valid_fn_char[VF_FN_MAX_CHAR - VF_FN_MIN_CHAR] = {
    VF_FN_CHAR_VALID_LONG,                            //!<  (Space)
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< !
    VF_FN_CHAR_INVALID,                               //!< "
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< #
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< $
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< %
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< &
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< '
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< (
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< )
    VF_FN_CHAR_INVALID,                               //!< *
    VF_FN_CHAR_VALID_LONG,                            //!< +
    VF_FN_CHAR_VALID_LONG,                            //!< ,
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< -
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< .
    VF_FN_CHAR_INVALID,                               //!< /
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 0
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 1
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 2
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 3
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 4
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 5
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 6
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 7
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 8
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< 9
    VF_FN_CHAR_INVALID,                               //!< :
    VF_FN_CHAR_VALID_LONG,                            //!< ;
    VF_FN_CHAR_INVALID,                               //!< <
    VF_FN_CHAR_VALID_LONG,                            //!< =
    VF_FN_CHAR_INVALID,                               //!< >
    VF_FN_CHAR_INVALID,                               //!< ?
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< @
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< A
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< B
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< C
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< D
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< E
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< F
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< G
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< H
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< I
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< J
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< K
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< L
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< M
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< N
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< O
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< P
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< Q
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< R
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< S
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< T
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< U
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< V
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< W
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< X
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< Y
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< Z
    VF_FN_CHAR_VALID_LONG,                            //!< [
    VF_FN_CHAR_INVALID,                               //!< \ (Backslash)
    VF_FN_CHAR_VALID_LONG,                            //!< ]
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< ^
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< _
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< `
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< a
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< b
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< c
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< d
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< e
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< f
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< g
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< h
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< i
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< j
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< k
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< l
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< m
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< n
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< o
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< p
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< q
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< r
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< s
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< t
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< u
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< v
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< w
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< x
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< y
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< z
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< {
    VF_FN_CHAR_INVALID,                               //!< |
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< }
    (VF_FN_CHAR_VALID_LONG | VF_FN_CHAR_VALID_SHORT), //!< ~
    VF_FN_CHAR_INVALID                                //!< DEL
};
